# Generated by Django 3.2.10 on 2021-12-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsData',
            fields=[
                ('jobid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('job_href', models.CharField(max_length=255)),
                ('job_name', models.CharField(max_length=255)),
                ('company_href', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('providesalary', models.CharField(blank=True, max_length=255, null=True)),
                ('workarea', models.CharField(blank=True, max_length=255, null=True)),
                ('company_type', models.CharField(blank=True, max_length=255, null=True)),
                ('jobwelf', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('companysize', models.CharField(blank=True, max_length=255, null=True)),
                ('companyind', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'jobs_data',
                'managed': False,
            },
        ),
    ]
